# Generated by Django 5.1.4 on 2025-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=140)),
                ('middle', models.CharField(blank=True, max_length=140)),
                ('last', models.CharField(max_length=140)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=140)),
                ('mobile', models.CharField(max_length=15)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
