# Generated by Django 5.1.4 on 2025-05-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='Login',
        ),
    ]
